environment:
  VisualStudioVersion: 11.0

version: 37.0.0.CI{build}
  
shallow_clone: true

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: .\build.ps1
  
# Disable tests
test: off

artifacts:
  - path: NuGet\*.nupkg